set search_path to data_sci

DROP TABLE if EXISTS emails

create table emails (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
email text
)

insert into emails
(email)
VALUES
('john@ms.com'),
('bob@ms.com'),
('john@ms.com');

insert into emails
(email)
VALUES
('john@ms.com'),
('bob@ms.com'),
('lalo@ms.com');


select * from emails;

delete from emails e
where e.id not in
	(select min(e2.id)
	from emails e2
	group by e2.email);


select * from emails;

-- This identifies the rows to be deleted
SELECT e.* from emails e 
 join emails e2 on e.email = e2.email
 where e2.id < e.id;


