set search_path to data_sci

create table products  (
product_id INTEGER   primary key GENERATED BY DEFAULT AS IDENTITY, 
store1     INTEGER     ,
store2     INTEGER     ,
store3    INTEGER   
)

insert into products
(store1, store2, store3)
VALUES
(95, 100, 105),
(70, null, 80)


select * from products




select product_id, 'Store1' as Store, store1 as Price
from products
where store1 is not null
union
(select product_id,  'Store2' as Store, store2 as Price
from products
where store2 is not null)
union
(select product_id,  'Store3' as Store, store3 as Price
from products
where store3 is not null)
order by product_id, store asc
