set search_path to data_sci

drop table logs

create table logs (
id integer primary key GENERATED BY DEFAULT AS IDENTITY,
log_num integer
)

insert into logs
(log_num)
(select trunc(random()*5) from generate_series(1,100) as num)

with lagcte as
	(select log_num,
	lag(log_num, 1) over(order by id) as lag1,
	lag(log_num, 2) over(order by id) as lag2
	from logs),
at_least_3 as
	(select log_num,
	(log_num - lag1) as diff1,
	(log_num - lag2) as diff2,
	case when (log_num - lag1)=0 AND
			(log_num - lag2 = 0 )then TRUE
	end  as found_three
	from lagcte)
select distinct log_num
from at_least_3
where found_three is TRUE

-- Simplified the query
with lagcte as
	(select log_num,
	lag(log_num, 1) over(order by id) as lag1,
	lag(log_num, 2) over(order by id) as lag2
	from logs)
select distinct log_num
from lagcte
where log_num = lag1 AND
		log_num = lag2
		

